# Generated by Django 4.2.1 on 2023-07-25 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_order_orderitem_review_shippingaddress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="shippingaddress",
            name="user",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
    ]
