export const CART_ITEM = {
  ADD: "CART_ADD_ITEM",
  REMOVE: "CART_REMOVE_ITEM",
  SAVE_SHIPPING_ADDRESS: "CART_SAVE_SHIPPING_ADDRESS",
  SAVE_PAYMENT_METHOD: "CART_SAVE_PAYMENT_METHOD",
  CLEAR_ITEMS: "CART_CLEAR_ITEMS",
};
