export const ORDER_CREATE = {
  REQUEST: "ORDER_CREATE_REQUEST",
  SUCCESS: "ORDER_CREATE_SUCCESS",
  FAIL: "ORDER_CREATE_FAIL",
  RESET: "ORDER_CREATE_RESET",
};

export const ORDER_DETAILS = {
  REQUEST: "ORDER_DETAILS_REQUEST",
  SUCCESS: "ORDER_DETAILS_SUCCESS",
  FAIL: "ORDER_DETAILS_FAIL",
};

export const ORDER_LIST = {
  REQUEST: "ORDER_LIST_REQUEST",
  SUCCESS: "ORDER_LIST_SUCCESS",
  FAIL: "ORDER_LIST_FAIL",
  RESET: "ORDER_LIST_RESET",
};
