export const USER_LOGIN = {
  REQUEST: "USER_LOGIN_REQUEST",
  SUCCESS: "USER_LOGIN_SUCCESS",
  FAIL: "USER_LOGIN_FAIL",
  LOGOUT: "USER_LOGOUT",
};

export const USER_REGISTER = {
  REQUEST: "USER_REGISTER_REQUEST",
  SUCCESS: "USER_REGISTER_SUCCESS",
  FAIL: "USER_REGISTER_FAIL",
  LOGOUT: "USER_LOGOUT",
};

export const USER_DETAILS = {
  REQUEST: "USER_DETAILS_REQUEST",
  SUCCESS: "USER_DETAILS_SUCCESS",
  FAIL: "USER_DETAILS_FAIL",
  RESET: "USER_DETAILS_RESET",
};

export const UPDATE_PROFILE = {
  REQUEST: "UPDATE_PROFILE_REQUEST",
  SUCCESS: "UPDATE_PROFILE_SUCCESS",
  FAIL: "UPDATE_PROFILE_FAIL",
  RESET: "UPDATE_PROFILE_RESET",
};
