# Generated by Django 4.2.1 on 2023-05-26 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_reviews',
            new_name='reviews_count',
        ),
    ]
